*** Settings ***
Documentation    This file has dictionaries for booking data used in test cases
Resource    ../common/super.resource

*** Variables ***

&{BOOKING_INFO}
    ...    input.time=09:30
    ...    input.duration=30
    ...    input.reason=New patient consultation

&{DEBTOR_INFO}
    ...    input.debtor.title=MR
    ...    input.debtor.surname=Smith
    ...    input.debtor.firstname=Alex
    ...    input.debtor.initials=AS
    ...    input.debtor.idnumber=9001015800081
    ...    input.debtor.gender=Male
    ...    input.debtor.cell=0823456789

&{PATIENT_INFO}
    ...    input.patient.title=MR
    ...    input.patient.surname=Smith
    ...    input.patient.firstname=Alex
    ...    input.patient.initials=AS
    ...    input.patient.idnumber=9001015800081
    ...    input.patient.gender=Male
    ...    input.patient.cell=0823456789
    ...    input.patient.dob=1990-01-01

&{EXPECTED_DATA}
    ...    debtor_name=MR Smith, AS, Alex
    ...    cell_no=0823456789
    ...    timeslot=09:30
